// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwTMu1wnXp8d53MYuIugBpS6V7gH7EC_o',
    appId: '1:486199853412:web:307758e8d415b46ac2ba71',
    messagingSenderId: '486199853412',
    projectId: 'shuttle-application',
    authDomain: 'shuttle-application.firebaseapp.com',
    storageBucket: 'shuttle-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALyj8vSRuuIulF303rx1BWFX0oe4AhK0k',
    appId: '1:486199853412:android:a3a0c201be39e13fc2ba71',
    messagingSenderId: '486199853412',
    projectId: 'shuttle-application',
    storageBucket: 'shuttle-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEG08Bbg8E7Tsu3HDyj-ynBAZuhPgck9E',
    appId: '1:486199853412:ios:92bf9adfcac64957c2ba71',
    messagingSenderId: '486199853412',
    projectId: 'shuttle-application',
    storageBucket: 'shuttle-application.appspot.com',
    androidClientId: '486199853412-m6o2vl8bi3cjsnt1q34ureg93oi6bq54.apps.googleusercontent.com',
    iosClientId: '486199853412-0fo7fi6fd09s2i4m1l6bt42mlr1jshbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shuttleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEG08Bbg8E7Tsu3HDyj-ynBAZuhPgck9E',
    appId: '1:486199853412:ios:92bf9adfcac64957c2ba71',
    messagingSenderId: '486199853412',
    projectId: 'shuttle-application',
    storageBucket: 'shuttle-application.appspot.com',
    androidClientId: '486199853412-m6o2vl8bi3cjsnt1q34ureg93oi6bq54.apps.googleusercontent.com',
    iosClientId: '486199853412-0fo7fi6fd09s2i4m1l6bt42mlr1jshbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shuttleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwTMu1wnXp8d53MYuIugBpS6V7gH7EC_o',
    appId: '1:486199853412:web:18f12ac346bb596ec2ba71',
    messagingSenderId: '486199853412',
    projectId: 'shuttle-application',
    authDomain: 'shuttle-application.firebaseapp.com',
    storageBucket: 'shuttle-application.appspot.com',
  );

}